function(file_download files output)
    foreach (file IN LISTS ${files})
        string(REPLACE "|" ";" parts ${file})
        list(GET parts 0 url)
        list(GET parts 1 hash)
        get_filename_component(filename ${url} NAME)

        set(filepath "${output}/${filename}")
        if (NOT EXISTS ${filepath})
            message(STATUS "Downloading file from ${url}")
            file(DOWNLOAD ${url} ${filepath} EXPECTED_HASH SHA256=${hash} SHOW_PROGRESS)
        endif ()
    endforeach ()
endfunction()

function(github_file_download files output repo)
    foreach (file IN LISTS ${files})
        string(REPLACE "|" ";" parts ${file})
        list(GET parts 0 filename)
        list(GET parts 1 hash)

        set(url https://raw.githubusercontent.com/${repo}/master/${filename})
        set(filepath "${output}/${filename}")
        if (NOT EXISTS ${filepath})
            message(STATUS "Downloading file from ${url}")
            file(DOWNLOAD ${url} ${filepath} EXPECTED_HASH SHA256=${hash} SHOW_PROGRESS)
        endif ()
    endforeach ()
endfunction()
